### ISSUE TITLE
Create full suite of Katacoda tutorials

### ISSUE THREAD

**Issue by autodidaddict** [wasmCloud/tutorials#4]
We want to be able to walk people through all kinds of tutorial scenarios, some of which might be difficult to reproduce on a developer workstation. Having the interactive shell plus documentation right there makes for a compelling introductory experience. More specifications on what we want to create will be forthcoming, though it should all be based on 0.15.0+ and later content.

**Comment by jordan-rash** [comment]
Here is the tracking sheet for what we have previously discussed.  https://docs.google.com/spreadsheets/d/1Ua4jG_Y2qPkcATtrA-vpFaZPUmPaTnI05ny2-ORqozk/edit?usp=sharing

More collaboration needed

**Comment by autodidaddict** [comment]
There is/was a google doc that liam had been using that had a ton of notes
we took on tutorials and their content.

**Comment by jordan-rash** [comment]
Thanks @autodidaddict, I have moved all of those notes into the Google sheet!

> There is/was a google doc that liam had been using that had a ton of notes we took on tutorials and their content.

**Comment by jordan-rash** [comment]
Initial set of tutorials identified and draft PRs created: #7 #8 #9 #10 #11
